[package]
name = "mcrs_render"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bytemuck = "1.16"
dot_vox = "5.1.1"

# todo: remove this and implement manually
block-mesh = "0.2"

mcrs_universe = { path = "../mcrs_universe" }
mcrs_physics = {path = "../mcrs_physics/"}
