[package]
name = "mcrs_render"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"
bytemuck = "1.14.0"
dot_vox = "5.1.1"

mcrs_storage = { path = "../mcrs_storage" }
mcrs_blueprints = { path = "../mcrs_blueprints" }
mcrs_flag_bank = { path = "../mcrs_flag_bank" }
