[package]
name = "voxel-experiment"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"
bevy_egui = "0.24.0"
tracing = "0.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
bevy-inspector-egui = "0.22.1"
noise = "0.8.2"

mcrs_core = { path = "crates/mcrs_core" }
mcrs_physics = { path = "crates/mcrs_physics" }
mcrs_render = { path = "crates/mcrs_render" }
mcrs_debug = { path = "crates/mcrs_debug" }
mcrs_storage = { path = "crates/mcrs_storage" }
mcrs_chemistry = { path = "crates/mcrs_chemistry" }
mcrs_input = { path = "crates/mcrs_input" }
mcrs_blueprints = { path = "crates/mcrs_blueprints" }
mcrs_net = { path = "crates/mcrs_net" }
mcrs_settings = { path = "crates/mcrs_settings" }

[workspace]
members = ["crates/*"]
exclude = ["tools/image_to_voxel_cube"]
