[package]
name = "voxel-experiment"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"
bevy_egui = "0.23.0"
egui_plot = "0.23.0"
bevy_flycam = "0.12.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
renet = { version = "0.0.14", features = ["serde"] }
bevy_renet = { version = "0.0.10", features = ["serde"] }
serde = "1.0.193"
bincode = "1.3.3"

voxel_render = { path = "crates/voxel_render" }
voxel_storage = { path = "crates/voxel_storage" }
voxel_physics = { path = "crates/voxel_physics" }
voxel_flag_bank = { path = "crates/voxel_flag_bank" }
voxel_automata = { path = "crates/voxel_automata" }
bytemuck = "1.14.0"

[workspace]
members = ["crates/*"]
