[package]
name = "voxel-experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
bevy_egui = "0.23.0"
bevy_flycam = "0.12.0"
rand = "0.8.5"
rand_chacha = "0.3.1"

voxel_render = { path = "crates/voxel_render" }
voxel_storage = { path = "crates/voxel_storage" }
voxel_physics = { path = "crates/voxel_physics" }

[workspace]
members = ["crates/*"]
