[package]
name = "mcrs_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"
bytemuck = "1.14.0"

mcrs_flag_bank = { path = "../mcrs_flag_bank" }
mcrs_blueprints = { path = "../mcrs_blueprints" }
