[package]
name = "mcrs_universe"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
bytemuck = "1.16"
ron = "0.8"
serde = { version = "1", features = ["derive"] }

mcrs_macros = { path = "../mcrs_macros" }

