[package]
name = "mcrs_net"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
renet = "1.0"
bevy_renet = "1.0"
serde = "1"
bincode = "1.3.3"
bytemuck = "1.16"

mcrs_universe = { path = "../mcrs_universe" }
mcrs_physics = { path = "../mcrs_physics" }
