[package]
name = "voxel_render"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"
bytemuck = "1.14.0"
dot_vox = "5.1.1"

voxel_storage = { path = "../voxel_storage" }
voxel_flag_bank = { path = "../voxel_flag_bank" }